version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ocr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  ocr-backend:
    container_name: ocr-backend
    build:
      context: ./Backend/
      dockerfile: .Dockerfile
    ports:
      - 5053:5053
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  ocr-frontend:
    container_name: ocr-frontend
    build:
      context: ./Frontend/
      dockerfile: .Dockerfile
    ports:
      - 4200:4200